/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test1;

import java.awt.Toolkit;

/**
 *
 * @author $$Goutham...!!$$
 */
public class Final extends javax.swing.JFrame {

    /**
     * Creates new form Final
     */
    public Final() {
         this.setUndecorated(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_gang = new javax.swing.JLabel();
        lbl_typh = new javax.swing.JLabel();
        lbl_blast = new javax.swing.JLabel();
        lbl_vene = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_pname = new javax.swing.JLabel();
        lbl_chari = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        btn_play = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl_gang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go5.jpg"))); // NOI18N
        getContentPane().add(lbl_gang);
        lbl_gang.setBounds(1020, 460, 570, 560);

        lbl_typh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go4typh.jpg"))); // NOI18N
        lbl_typh.setText("jLabel5");
        getContentPane().add(lbl_typh);
        lbl_typh.setBounds(910, 440, 800, 610);

        lbl_blast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go2.jpg"))); // NOI18N
        getContentPane().add(lbl_blast);
        lbl_blast.setBounds(980, 460, 600, 560);

        lbl_vene.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go1.jpg"))); // NOI18N
        getContentPane().add(lbl_vene);
        lbl_vene.setBounds(960, 440, 640, 600);

        jLabel4.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabel4.setText("PLAY AGAIN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1090, 410, 270, 70);

        jLabel3.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabel3.setText("EXIT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 710, 130, 50);

        jLabel2.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabel2.setText("WINS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 280, 260, 110);

        lbl_pname.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        lbl_pname.setText("name");
        getContentPane().add(lbl_pname);
        lbl_pname.setBounds(680, 210, 340, 70);

        lbl_chari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go4 char.png"))); // NOI18N
        getContentPane().add(lbl_chari);
        lbl_chari.setBounds(880, 460, 900, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/final.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        btn_exit.setText("jButton1");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(120, 690, 490, 300);

        btn_play.setText("jButton2");
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });
        getContentPane().add(btn_play);
        btn_play.setBounds(960, 370, 670, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        System.exit(123);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btn_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_play;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_blast;
    private javax.swing.JLabel lbl_chari;
    private javax.swing.JLabel lbl_gang;
    private javax.swing.JLabel lbl_pname;
    private javax.swing.JLabel lbl_typh;
    private javax.swing.JLabel lbl_vene;
    // End of variables declaration//GEN-END:variables
}
