/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test1;
import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Toolkit;
import java.io.File;
/**
 *
 * @author $$Goutham...!!$$
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        File wavFile = new File("C:\\MyProjects\\Pokemon\\poke\\Pokemon\\PokemonGame\\src\\Audios\\thunder_sound.wav");
            AudioClip sound = null;            
            try{sound = Applet.newAudioClip(wavFile.toURL());}
            catch(Exception e){e.printStackTrace();}
            sound.play();
        this.setUndecorated(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize); 
        System.out.println("x==="+xsize+"y===="+ysize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tostart = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();
        lbl_intropokemon = new javax.swing.JLabel();
        lbl_thunder = new javax.swing.JLabel();
        lb_intro1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl_tostart.setFont(new java.awt.Font("Nirmala UI", 3, 18)); // NOI18N
        lbl_tostart.setForeground(new java.awt.Color(204, 0, 0));
        lbl_tostart.setText("CLICK ON THE POKEBALL TO START");
        getContentPane().add(lbl_tostart);
        lbl_tostart.setBounds(260, 490, 350, 70);

        btn_start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pb3.png"))); // NOI18N
        btn_start.setText("jButton1");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        getContentPane().add(btn_start);
        btn_start.setBounds(310, 360, 200, 140);

        lbl_intropokemon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pk.gif"))); // NOI18N
        lbl_intropokemon.setText("jLabel3");
        getContentPane().add(lbl_intropokemon);
        lbl_intropokemon.setBounds(180, 130, 510, 220);

        lbl_thunder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/th1.gif"))); // NOI18N
        getContentPane().add(lbl_thunder);
        lbl_thunder.setBounds(270, 110, 590, 290);

        lb_intro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/intro2.jpg"))); // NOI18N
        getContentPane().add(lb_intro1);
        lb_intro1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
          File wavFile = new File("C:\\MyProjects\\Pokemon\\poke\\Pokemon\\PokemonGame\\src\\Audios\\pikach.wav");
            AudioClip sound = null;            
            try{sound = Applet.newAudioClip(wavFile.toURL());}
            catch(Exception e){e.printStackTrace();}
            sound.play();

        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel lb_intro1;
    private javax.swing.JLabel lbl_intropokemon;
    private javax.swing.JLabel lbl_thunder;
    private javax.swing.JLabel lbl_tostart;
    // End of variables declaration//GEN-END:variables
}
