/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test1;

import java.awt.Toolkit;

/**
 *
 * @author $$Goutham...!!$$
 */
public class Frame5 extends javax.swing.JFrame {

    /**
     * Creates new form Frame5
     */
    public Frame5() {
        this.setUndecorated(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
    }
    
    void turnOff(){
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typhat4p2 = new javax.swing.JLabel();
        typhat4p1 = new javax.swing.JLabel();
        typhat3p2 = new javax.swing.JLabel();
        typhat3p1 = new javax.swing.JLabel();
        lbl_typhat2p2 = new javax.swing.JLabel();
        lbl_typhat2p1 = new javax.swing.JLabel();
        lbl_typhat1p2 = new javax.swing.JLabel();
        lbl_typhat1p1 = new javax.swing.JLabel();
        lbl_typhp2 = new javax.swing.JLabel();
        lbl_typhp1 = new javax.swing.JLabel();
        lbl_genat4p2 = new javax.swing.JLabel();
        lbl_genat4p1 = new javax.swing.JLabel();
        lbl_genat3p2 = new javax.swing.JLabel();
        lbl_genat3p1 = new javax.swing.JLabel();
        lbl_genat2p2 = new javax.swing.JLabel();
        lbl_genat2p1 = new javax.swing.JLabel();
        lbl_genat1p2 = new javax.swing.JLabel();
        lbl_genat1p1 = new javax.swing.JLabel();
        lbl_genp2 = new javax.swing.JLabel();
        lbl_genp1 = new javax.swing.JLabel();
        lbl_chariat4p2 = new javax.swing.JLabel();
        lbl_chariat4p1 = new javax.swing.JLabel();
        lbl_chariat3p2 = new javax.swing.JLabel();
        lbl_chariat3p1 = new javax.swing.JLabel();
        lbl_chariat2p2 = new javax.swing.JLabel();
        lbl_chariat2p1 = new javax.swing.JLabel();
        lbl_chariat1p2 = new javax.swing.JLabel();
        lbl_chariat1p1 = new javax.swing.JLabel();
        lbl_charip2 = new javax.swing.JLabel();
        lbl_charip1 = new javax.swing.JLabel();
        lbl_blastat4p2 = new javax.swing.JLabel();
        lbl_blastat4p1 = new javax.swing.JLabel();
        lbl_blastat3p2 = new javax.swing.JLabel();
        lbl_blastat3p1 = new javax.swing.JLabel();
        lbl_blastat2p2 = new javax.swing.JLabel();
        lbl_blastat2p1 = new javax.swing.JLabel();
        lbl_blastat1p2 = new javax.swing.JLabel();
        lbl_blastat1p1 = new javax.swing.JLabel();
        lbl_veat1p1 = new javax.swing.JLabel();
        lbl_veat1p2 = new javax.swing.JLabel();
        lbl_venat4p2 = new javax.swing.JLabel();
        lbl_venat4p1 = new javax.swing.JLabel();
        lbl_venat2p1 = new javax.swing.JLabel();
        lbl_venat2p2 = new javax.swing.JLabel();
        lbl_blastp2 = new javax.swing.JLabel();
        lbl_blastp1 = new javax.swing.JLabel();
        lbl_venp2 = new javax.swing.JLabel();
        lbl_venp1 = new javax.swing.JLabel();
        lbl_veat3p2 = new javax.swing.JLabel();
        lbl_veat3p1 = new javax.swing.JLabel();
        lbl_frame5back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        typhat4p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/typat4.gif"))); // NOI18N
        getContentPane().add(typhat4p2);
        typhat4p2.setBounds(970, 400, 530, 320);

        typhat4p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/typat4.gif"))); // NOI18N
        getContentPane().add(typhat4p1);
        typhat4p1.setBounds(420, 410, 530, 320);

        typhat3p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/typhat3.gif"))); // NOI18N
        typhat3p2.setText("jLabel1");
        getContentPane().add(typhat3p2);
        typhat3p2.setBounds(960, 410, 320, 280);

        typhat3p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/typhat3.gif"))); // NOI18N
        typhat3p1.setText("jLabel1");
        getContentPane().add(typhat3p1);
        typhat3p1.setBounds(600, 410, 320, 280);

        lbl_typhat2p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/typat2.gif"))); // NOI18N
        getContentPane().add(lbl_typhat2p2);
        lbl_typhat2p2.setBounds(980, 440, 320, 250);

        lbl_typhat2p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/typat2.gif"))); // NOI18N
        getContentPane().add(lbl_typhat2p1);
        lbl_typhat2p1.setBounds(620, 440, 320, 250);

        lbl_typhat1p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/typat1.gif"))); // NOI18N
        getContentPane().add(lbl_typhat1p2);
        lbl_typhat1p2.setBounds(990, 410, 350, 310);

        lbl_typhat1p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/typat1.gif"))); // NOI18N
        getContentPane().add(lbl_typhat1p1);
        lbl_typhat1p1.setBounds(610, 410, 350, 310);

        lbl_typhp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go4typh.jpg"))); // NOI18N
        getContentPane().add(lbl_typhp2);
        lbl_typhp2.setBounds(1120, 270, 800, 620);

        lbl_typhp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go4typh.jpg"))); // NOI18N
        getContentPane().add(lbl_typhp1);
        lbl_typhp1.setBounds(0, 270, 800, 620);

        lbl_genat4p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/genat4.gif"))); // NOI18N
        getContentPane().add(lbl_genat4p2);
        lbl_genat4p2.setBounds(1030, 460, 230, 240);

        lbl_genat4p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/genat4.gif"))); // NOI18N
        getContentPane().add(lbl_genat4p1);
        lbl_genat4p1.setBounds(650, 460, 230, 240);

        lbl_genat3p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/getat3.gif"))); // NOI18N
        getContentPane().add(lbl_genat3p2);
        lbl_genat3p2.setBounds(970, 440, 350, 270);

        lbl_genat3p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/getat3.gif"))); // NOI18N
        getContentPane().add(lbl_genat3p1);
        lbl_genat3p1.setBounds(570, 450, 350, 270);

        lbl_genat2p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/genat2.gif"))); // NOI18N
        lbl_genat2p2.setText("jLabel1");
        getContentPane().add(lbl_genat2p2);
        lbl_genat2p2.setBounds(980, 460, 300, 230);

        lbl_genat2p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/genat2.gif"))); // NOI18N
        lbl_genat2p1.setText("jLabel1");
        getContentPane().add(lbl_genat2p1);
        lbl_genat2p1.setBounds(590, 460, 300, 230);

        lbl_genat1p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/genat1.gif"))); // NOI18N
        getContentPane().add(lbl_genat1p2);
        lbl_genat1p2.setBounds(970, 380, 340, 400);

        lbl_genat1p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/genat1.gif"))); // NOI18N
        getContentPane().add(lbl_genat1p1);
        lbl_genat1p1.setBounds(580, 380, 340, 400);

        lbl_genp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go5.jpg"))); // NOI18N
        getContentPane().add(lbl_genp2);
        lbl_genp2.setBounds(1340, 40, 570, 910);

        lbl_genp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go5.jpg"))); // NOI18N
        getContentPane().add(lbl_genp1);
        lbl_genp1.setBounds(0, 10, 570, 910);

        lbl_chariat4p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/charat4.gif"))); // NOI18N
        getContentPane().add(lbl_chariat4p2);
        lbl_chariat4p2.setBounds(970, 470, 360, 200);

        lbl_chariat4p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/charat4.gif"))); // NOI18N
        getContentPane().add(lbl_chariat4p1);
        lbl_chariat4p1.setBounds(570, 470, 360, 200);

        lbl_chariat3p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/charat3.gif"))); // NOI18N
        getContentPane().add(lbl_chariat3p2);
        lbl_chariat3p2.setBounds(970, 430, 400, 270);

        lbl_chariat3p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/charat3.gif"))); // NOI18N
        getContentPane().add(lbl_chariat3p1);
        lbl_chariat3p1.setBounds(530, 440, 400, 270);

        lbl_chariat2p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/charat2.gif"))); // NOI18N
        getContentPane().add(lbl_chariat2p2);
        lbl_chariat2p2.setBounds(960, 450, 390, 250);

        lbl_chariat2p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/charat2.gif"))); // NOI18N
        getContentPane().add(lbl_chariat2p1);
        lbl_chariat2p1.setBounds(560, 450, 390, 250);

        lbl_chariat1p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/charat1.gif"))); // NOI18N
        getContentPane().add(lbl_chariat1p2);
        lbl_chariat1p2.setBounds(970, 420, 290, 280);

        lbl_chariat1p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/charat1.gif"))); // NOI18N
        getContentPane().add(lbl_chariat1p1);
        lbl_chariat1p1.setBounds(580, 420, 290, 280);

        lbl_charip2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go4 char.png"))); // NOI18N
        getContentPane().add(lbl_charip2);
        lbl_charip2.setBounds(1040, 90, 880, 690);

        lbl_charip1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go4 char.png"))); // NOI18N
        getContentPane().add(lbl_charip1);
        lbl_charip1.setBounds(-30, 120, 880, 690);

        lbl_blastat4p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blastat4.gif"))); // NOI18N
        getContentPane().add(lbl_blastat4p2);
        lbl_blastat4p2.setBounds(960, 420, 510, 270);

        lbl_blastat4p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blastat4.gif"))); // NOI18N
        getContentPane().add(lbl_blastat4p1);
        lbl_blastat4p1.setBounds(450, 420, 510, 270);

        lbl_blastat3p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blasat3.gif"))); // NOI18N
        getContentPane().add(lbl_blastat3p2);
        lbl_blastat3p2.setBounds(1010, 440, 370, 260);

        lbl_blastat3p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blasat3.gif"))); // NOI18N
        getContentPane().add(lbl_blastat3p1);
        lbl_blastat3p1.setBounds(580, 430, 370, 260);

        lbl_blastat2p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blasat2.gif"))); // NOI18N
        getContentPane().add(lbl_blastat2p2);
        lbl_blastat2p2.setBounds(1010, 440, 330, 240);

        lbl_blastat2p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blasat2.gif"))); // NOI18N
        getContentPane().add(lbl_blastat2p1);
        lbl_blastat2p1.setBounds(590, 440, 330, 240);

        lbl_blastat1p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blasat1.gif"))); // NOI18N
        getContentPane().add(lbl_blastat1p2);
        lbl_blastat1p2.setBounds(1030, 440, 290, 270);

        lbl_blastat1p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blasat1.gif"))); // NOI18N
        getContentPane().add(lbl_blastat1p1);
        lbl_blastat1p1.setBounds(640, 430, 290, 270);

        lbl_veat1p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/venat2.gif"))); // NOI18N
        getContentPane().add(lbl_veat1p1);
        lbl_veat1p1.setBounds(680, 450, 200, 230);

        lbl_veat1p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/venat2.gif"))); // NOI18N
        getContentPane().add(lbl_veat1p2);
        lbl_veat1p2.setBounds(1040, 450, 200, 230);

        lbl_venat4p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/venat4.gif"))); // NOI18N
        getContentPane().add(lbl_venat4p2);
        lbl_venat4p2.setBounds(960, 380, 510, 360);

        lbl_venat4p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/venat4.gif"))); // NOI18N
        getContentPane().add(lbl_venat4p1);
        lbl_venat4p1.setBounds(450, 370, 510, 360);

        lbl_venat2p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/venat3.gif"))); // NOI18N
        lbl_venat2p1.setText("jLabel1");
        getContentPane().add(lbl_venat2p1);
        lbl_venat2p1.setBounds(660, 440, 300, 230);

        lbl_venat2p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/venat3.gif"))); // NOI18N
        lbl_venat2p2.setText("jLabel1");
        getContentPane().add(lbl_venat2p2);
        lbl_venat2p2.setBounds(960, 440, 300, 230);

        lbl_blastp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go2.jpg"))); // NOI18N
        getContentPane().add(lbl_blastp2);
        lbl_blastp2.setBounds(1280, 200, 610, 570);

        lbl_blastp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go2.jpg"))); // NOI18N
        getContentPane().add(lbl_blastp1);
        lbl_blastp1.setBounds(70, 190, 610, 570);

        lbl_venp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go1.jpg"))); // NOI18N
        getContentPane().add(lbl_venp2);
        lbl_venp2.setBounds(1270, 220, 640, 550);

        lbl_venp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go1.jpg"))); // NOI18N
        getContentPane().add(lbl_venp1);
        lbl_venp1.setBounds(30, 210, 640, 550);

        lbl_veat3p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/venat2.gif"))); // NOI18N
        getContentPane().add(lbl_veat3p2);
        lbl_veat3p2.setBounds(1040, 450, 200, 230);

        lbl_veat3p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/venat2.gif"))); // NOI18N
        getContentPane().add(lbl_veat3p1);
        lbl_veat3p1.setBounds(680, 450, 200, 230);

        lbl_frame5back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/battle.jpg"))); // NOI18N
        getContentPane().add(lbl_frame5back);
        lbl_frame5back.setBounds(0, 10, 1920, 1200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_blastat1p1;
    private javax.swing.JLabel lbl_blastat1p2;
    private javax.swing.JLabel lbl_blastat2p1;
    private javax.swing.JLabel lbl_blastat2p2;
    private javax.swing.JLabel lbl_blastat3p1;
    private javax.swing.JLabel lbl_blastat3p2;
    private javax.swing.JLabel lbl_blastat4p1;
    private javax.swing.JLabel lbl_blastat4p2;
    private javax.swing.JLabel lbl_blastp1;
    private javax.swing.JLabel lbl_blastp2;
    private javax.swing.JLabel lbl_chariat1p1;
    private javax.swing.JLabel lbl_chariat1p2;
    private javax.swing.JLabel lbl_chariat2p1;
    private javax.swing.JLabel lbl_chariat2p2;
    private javax.swing.JLabel lbl_chariat3p1;
    private javax.swing.JLabel lbl_chariat3p2;
    private javax.swing.JLabel lbl_chariat4p1;
    private javax.swing.JLabel lbl_chariat4p2;
    private javax.swing.JLabel lbl_charip1;
    private javax.swing.JLabel lbl_charip2;
    private javax.swing.JLabel lbl_frame5back;
    private javax.swing.JLabel lbl_genat1p1;
    private javax.swing.JLabel lbl_genat1p2;
    private javax.swing.JLabel lbl_genat2p1;
    private javax.swing.JLabel lbl_genat2p2;
    private javax.swing.JLabel lbl_genat3p1;
    private javax.swing.JLabel lbl_genat3p2;
    private javax.swing.JLabel lbl_genat4p1;
    private javax.swing.JLabel lbl_genat4p2;
    private javax.swing.JLabel lbl_genp1;
    private javax.swing.JLabel lbl_genp2;
    private javax.swing.JLabel lbl_typhat1p1;
    private javax.swing.JLabel lbl_typhat1p2;
    private javax.swing.JLabel lbl_typhat2p1;
    private javax.swing.JLabel lbl_typhat2p2;
    private javax.swing.JLabel lbl_typhp1;
    private javax.swing.JLabel lbl_typhp2;
    private javax.swing.JLabel lbl_veat1p1;
    private javax.swing.JLabel lbl_veat1p2;
    private javax.swing.JLabel lbl_veat3p1;
    private javax.swing.JLabel lbl_veat3p2;
    private javax.swing.JLabel lbl_venat2p1;
    private javax.swing.JLabel lbl_venat2p2;
    private javax.swing.JLabel lbl_venat4p1;
    private javax.swing.JLabel lbl_venat4p2;
    private javax.swing.JLabel lbl_venp1;
    private javax.swing.JLabel lbl_venp2;
    private javax.swing.JLabel typhat3p1;
    private javax.swing.JLabel typhat3p2;
    private javax.swing.JLabel typhat4p1;
    private javax.swing.JLabel typhat4p2;
    // End of variables declaration//GEN-END:variables
}
