/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test1;

import java.awt.Toolkit;

/**
 *
 * @author $$Goutham...!!$$
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    
    public Frame2() {
        this.setUndecorated(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        lbl_blastgif.setVisible(false);
        lbl_charigif.setVisible(false);
        lbl_gengif.setVisible(false);
         lbl_vengifP1.setVisible(false);
           lbl_vengifP2.setVisible(false);
        lbl_charigifp2.setVisible(false);
        lbl_gengifp2.setVisible(false);
        lbl_typhgifp1.setVisible(false);
         lbl_typhgifp2.setVisible(false);
        lbl_blastgifp2.setVisible(false);
          btn_next.setVisible(false);
          chbk_p1.setEnabled(false);
          chbk_p2.setEnabled(false);
          lbl_next.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_next = new javax.swing.JButton();
        lbl_next = new javax.swing.JLabel();
        chbk_p2 = new javax.swing.JCheckBox();
        btn_typhp2 = new javax.swing.JButton();
        chbk_p1 = new javax.swing.JCheckBox();
        lbl_typhgifp2 = new javax.swing.JLabel();
        lbl_typhgifp1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_p2pokename1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_p1pokename = new javax.swing.JLabel();
        lbl_charigifp2 = new javax.swing.JLabel();
        lbl_mkcp2 = new javax.swing.JLabel();
        lbl_gengifp2 = new javax.swing.JLabel();
        lbl_blastgifp2 = new javax.swing.JLabel();
        lbl_vengifP2 = new javax.swing.JLabel();
        lbl_vengifP1 = new javax.swing.JLabel();
        lbl_blastgif = new javax.swing.JLabel();
        lbl_charigif = new javax.swing.JLabel();
        btn_blastp2 = new javax.swing.JButton();
        btn_genp2 = new javax.swing.JButton();
        btn_charip2 = new javax.swing.JButton();
        btn_venp2 = new javax.swing.JButton();
        btn_venp1 = new javax.swing.JButton();
        btn_charip1 = new javax.swing.JButton();
        btn_blastp1 = new javax.swing.JButton();
        btn_genp1 = new javax.swing.JButton();
        btn_typhp1 = new javax.swing.JButton();
        lbl_mkc = new javax.swing.JLabel();
        lbl_gengif = new javax.swing.JLabel();
        lbl_select = new javax.swing.JLabel();
        lbl_back2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PokeBall.png"))); // NOI18N
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });
        getContentPane().add(btn_next);
        btn_next.setBounds(1650, 510, 80, 60);

        lbl_next.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        lbl_next.setForeground(new java.awt.Color(102, 0, 102));
        lbl_next.setText(" <==NEXT");
        getContentPane().add(lbl_next);
        lbl_next.setBounds(1750, 520, 130, 40);

        chbk_p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbk_p2ActionPerformed(evt);
            }
        });
        getContentPane().add(chbk_p2);
        chbk_p2.setBounds(1840, 1010, 25, 25);

        btn_typhp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Typhlosion-Pokemon-Go.png"))); // NOI18N
        btn_typhp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_typhp2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_typhp2);
        btn_typhp2.setBounds(1220, 550, 290, 400);

        chbk_p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbk_p1ActionPerformed(evt);
            }
        });
        getContentPane().add(chbk_p1);
        chbk_p1.setBounds(1840, 140, 30, 25);

        lbl_typhgifp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200.gif"))); // NOI18N
        getContentPane().add(lbl_typhgifp2);
        lbl_typhgifp2.setBounds(1590, 650, 310, 210);

        lbl_typhgifp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/200.gif"))); // NOI18N
        getContentPane().add(lbl_typhgifp1);
        lbl_typhgifp1.setBounds(1570, 230, 310, 210);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("PLAYER - 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 980, 140, 40);

        lbl_p2pokename1.setBackground(new java.awt.Color(255, 0, 153));
        lbl_p2pokename1.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        lbl_p2pokename1.setForeground(new java.awt.Color(0, 0, 204));
        lbl_p2pokename1.setText("Select Your Pokemon");
        getContentPane().add(lbl_p2pokename1);
        lbl_p2pokename1.setBounds(1570, 930, 280, 39);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("PLAYER - 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(600, 70, 140, 40);

        lbl_p1pokename.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        lbl_p1pokename.setForeground(new java.awt.Color(255, 0, 0));
        lbl_p1pokename.setText("Select Your Pokemon");
        getContentPane().add(lbl_p1pokename);
        lbl_p1pokename.setBounds(1570, 130, 280, 39);

        lbl_charigifp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gowthy.gif"))); // NOI18N
        lbl_charigifp2.setText("jLabel3");
        getContentPane().add(lbl_charigifp2);
        lbl_charigifp2.setBounds(1540, 640, 390, 210);

        lbl_mkcp2.setBackground(new java.awt.Color(0, 0, 0));
        lbl_mkcp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/makechoics12.jpg"))); // NOI18N
        getContentPane().add(lbl_mkcp2);
        lbl_mkcp2.setBounds(1530, 610, 420, 310);

        lbl_gengifp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gowthy3.gif"))); // NOI18N
        getContentPane().add(lbl_gengifp2);
        lbl_gengifp2.setBounds(1640, 570, 210, 340);

        lbl_blastgifp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gowthy2.gif"))); // NOI18N
        getContentPane().add(lbl_blastgifp2);
        lbl_blastgifp2.setBounds(1550, 620, 370, 230);

        lbl_vengifP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/venasaur.gif"))); // NOI18N
        getContentPane().add(lbl_vengifP2);
        lbl_vengifP2.setBounds(1610, 640, 260, 210);

        lbl_vengifP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/venasaur.gif"))); // NOI18N
        getContentPane().add(lbl_vengifP1);
        lbl_vengifP1.setBounds(1610, 240, 260, 210);

        lbl_blastgif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gowthy2.gif"))); // NOI18N
        getContentPane().add(lbl_blastgif);
        lbl_blastgif.setBounds(1560, 220, 370, 230);

        lbl_charigif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gowthy.gif"))); // NOI18N
        lbl_charigif.setText("jLabel3");
        getContentPane().add(lbl_charigif);
        lbl_charigif.setBounds(1550, 230, 390, 210);

        btn_blastp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Blastoise_4224305.png"))); // NOI18N
        btn_blastp2.setText("jButton3");
        btn_blastp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_blastp2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_blastp2);
        btn_blastp2.setBounds(610, 560, 280, 390);

        btn_genp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/094Gengar_OS_anime_3.png"))); // NOI18N
        btn_genp2.setText("jButton3");
        btn_genp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genp2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_genp2);
        btn_genp2.setBounds(920, 550, 280, 400);

        btn_charip2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/charizard.png"))); // NOI18N
        btn_charip2.setText("jButton2");
        btn_charip2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_charip2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_charip2);
        btn_charip2.setBounds(310, 570, 280, 390);

        btn_venp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/003Venusaur-Mega_XY_anime.png"))); // NOI18N
        btn_venp2.setText("jButton1");
        btn_venp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_venp2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_venp2);
        btn_venp2.setBounds(10, 570, 280, 390);

        btn_venp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/003Venusaur-Mega_XY_anime.png"))); // NOI18N
        btn_venp1.setText("jButton1");
        btn_venp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_venp1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_venp1);
        btn_venp1.setBounds(10, 140, 280, 390);

        btn_charip1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/charizard.png"))); // NOI18N
        btn_charip1.setText("jButton2");
        btn_charip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_charip1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_charip1);
        btn_charip1.setBounds(310, 140, 280, 390);

        btn_blastp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Blastoise_4224305.png"))); // NOI18N
        btn_blastp1.setText("jButton3");
        btn_blastp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_blastp1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_blastp1);
        btn_blastp1.setBounds(600, 140, 280, 390);

        btn_genp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/094Gengar_OS_anime_3.png"))); // NOI18N
        btn_genp1.setText("jButton3");
        btn_genp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genp1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_genp1);
        btn_genp1.setBounds(910, 130, 280, 400);

        btn_typhp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Typhlosion-Pokemon-Go.png"))); // NOI18N
        btn_typhp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_typhp1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_typhp1);
        btn_typhp1.setBounds(1210, 130, 290, 400);

        lbl_mkc.setBackground(new java.awt.Color(0, 0, 0));
        lbl_mkc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/makechoics12.jpg"))); // NOI18N
        getContentPane().add(lbl_mkc);
        lbl_mkc.setBounds(1530, 180, 420, 310);

        lbl_gengif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gowthy3.gif"))); // NOI18N
        getContentPane().add(lbl_gengif);
        lbl_gengif.setBounds(1640, 170, 210, 340);

        lbl_select.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/select.jpg"))); // NOI18N
        getContentPane().add(lbl_select);
        lbl_select.setBounds(-50, -40, 2070, 1180);

        lbl_back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pokemon-free-ash-ketchum_159367.jpg"))); // NOI18N
        getContentPane().add(lbl_back2);
        lbl_back2.setBounds(1, -4, 2010, 1160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_charip2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_charip2ActionPerformed
        // TODO add your handling code here:
        if(!chbk_p2.isSelected()){
        chbk_p2.setEnabled(true);
        lbl_p2pokename1.setText("Charizard");
        lbl_vengifP2.setVisible(false);
        lbl_charigifp2.setVisible(true);
        lbl_gengifp2.setVisible(false);
        lbl_mkcp2.setVisible(false);
        lbl_blastgifp2.setVisible(false);
        lbl_typhgifp2.setVisible(false);
        }
    }//GEN-LAST:event_btn_charip2ActionPerformed

    private void btn_charip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_charip1ActionPerformed
        // TODO add your handling code here:
        if(!chbk_p1.isSelected()){
        chbk_p1.setEnabled(true);
        lbl_typhgifp1.setVisible(false);
        lbl_p1pokename.setText("Charizard");
        lbl_mkc.setVisible(false);
        lbl_charigif.setVisible(true);
        lbl_blastgif.setVisible(false);
         lbl_gengif.setVisible(false);
         lbl_vengifP1.setVisible(false);
        }
    }//GEN-LAST:event_btn_charip1ActionPerformed

    private void btn_typhp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_typhp2ActionPerformed
        // TODO add your handling code here:
        if(!chbk_p2.isSelected()){
        chbk_p2.setEnabled(true);
        lbl_p2pokename1.setText("Typhlosion");
          lbl_mkcp2.setVisible(false);
        lbl_charigifp2.setVisible(false);
        lbl_blastgifp2.setVisible(false);
         lbl_gengifp2.setVisible(false);
         lbl_vengifP2.setVisible(false);
         lbl_typhgifp2.setVisible(true);}
    }//GEN-LAST:event_btn_typhp2ActionPerformed

    private void btn_typhp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_typhp1ActionPerformed
        // TODO add your handling code here:
        if(!chbk_p1.isSelected()){
        chbk_p1.setEnabled(true);
        lbl_mkc.setVisible(false);
        lbl_charigif.setVisible(false);
        lbl_blastgif.setVisible(false);
         lbl_gengif.setVisible(false);
         lbl_vengifP1.setVisible(false);
         lbl_typhgifp1.setVisible(true);
      lbl_p1pokename.setText("Typhlosion");
        }
    }//GEN-LAST:event_btn_typhp1ActionPerformed

    private void btn_blastp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_blastp1ActionPerformed
        // TODO add your handling code here:
        if(!chbk_p1.isSelected()){
        chbk_p1.setEnabled(true);
        lbl_typhgifp1.setVisible(false);
        lbl_p1pokename.setText("Blastoise");
        lbl_mkc.setVisible(false);
        lbl_charigif.setVisible(false);
        lbl_blastgif.setVisible(true);
         lbl_gengif.setVisible(false);
         lbl_vengifP1.setVisible(false);
        }
    }//GEN-LAST:event_btn_blastp1ActionPerformed

    private void btn_genp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genp1ActionPerformed
        // TODO add your handling code here:
        if(!chbk_p1.isSelected()){
        chbk_p1.setEnabled(true);
        lbl_typhgifp1.setVisible(false);
        lbl_p1pokename.setText("Gengar");
        lbl_mkc.setVisible(false);
        lbl_charigif.setVisible(false);
        lbl_blastgif.setVisible(false);
         lbl_gengif.setVisible(true);
         lbl_vengifP1.setVisible(false);
    }//GEN-LAST:event_btn_genp1ActionPerformed
    }
    private void btn_venp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_venp1ActionPerformed
        // TODO add your handling code here:
        if(!chbk_p1.isSelected()){
        chbk_p1.setEnabled(true);
        lbl_typhgifp1.setVisible(false);
        lbl_p1pokename.setText("Venusaur");
        lbl_blastgif.setVisible(false);
        lbl_charigif.setVisible(false);
        lbl_gengif.setVisible(false);
         lbl_vengifP1.setVisible(true);
         lbl_mkc.setVisible(false);}

    }//GEN-LAST:event_btn_venp1ActionPerformed

    private void btn_venp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_venp2ActionPerformed
        // TODO add your handling code here:
        if(!chbk_p2.isSelected()){
        chbk_p2.setEnabled(true);
        lbl_typhgifp2.setVisible(false);
        lbl_p2pokename1.setText("Venusaur");
        lbl_vengifP2.setVisible(true);
        lbl_charigifp2.setVisible(false);
        lbl_gengifp2.setVisible(false);
        lbl_mkcp2.setVisible(false);
        lbl_blastgifp2.setVisible(false);
        }
    }//GEN-LAST:event_btn_venp2ActionPerformed

    private void btn_blastp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_blastp2ActionPerformed
        // TODO add your handling code here:
        if(!chbk_p2.isSelected()){
        chbk_p2.setEnabled(true);
        lbl_typhgifp2.setVisible(false);
        lbl_p2pokename1.setText("Blastoise");
        lbl_vengifP2.setVisible(false);
        lbl_charigifp2.setVisible(false);
        lbl_gengifp2.setVisible(false);
        lbl_mkcp2.setVisible(false);
        lbl_blastgifp2.setVisible(true);}
    }//GEN-LAST:event_btn_blastp2ActionPerformed

    private void btn_genp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genp2ActionPerformed
        // TODO add your handling code here:
        if(!chbk_p2.isSelected()){
        chbk_p2.setEnabled(true);
        lbl_typhgifp2.setVisible(false);
        lbl_p2pokename1.setText("Gengar");
        lbl_vengifP2.setVisible(false);
        lbl_charigifp2.setVisible(false);
        lbl_gengifp2.setVisible(true);
        lbl_mkcp2.setVisible(false);
        lbl_blastgifp2.setVisible(false);}
    }//GEN-LAST:event_btn_genp2ActionPerformed

    private void chbk_p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbk_p1ActionPerformed
        // TODO add your handling code here:
        if(chbk_p2.isSelected() && chbk_p1.isSelected())
        {
            btn_next.setVisible(true);
            lbl_next.setVisible(true);
        }
        else
        {
            btn_next.setVisible(false);
            lbl_next.setVisible(false);
        }
    }//GEN-LAST:event_chbk_p1ActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
        new Frame4().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_nextActionPerformed

    private void chbk_p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbk_p2ActionPerformed
      // TODO add your handling code here:
      if(chbk_p2.isSelected() && chbk_p1.isSelected())
        {
            btn_next.setVisible(true);
            lbl_next.setVisible(true);
        }
        else
        {
            btn_next.setVisible(false);
            lbl_next.setVisible(false);
        }
    }//GEN-LAST:event_chbk_p2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_blastp1;
    private javax.swing.JButton btn_blastp2;
    private javax.swing.JButton btn_charip1;
    private javax.swing.JButton btn_charip2;
    private javax.swing.JButton btn_genp1;
    private javax.swing.JButton btn_genp2;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_typhp1;
    private javax.swing.JButton btn_typhp2;
    private javax.swing.JButton btn_venp1;
    private javax.swing.JButton btn_venp2;
    private javax.swing.JCheckBox chbk_p1;
    private javax.swing.JCheckBox chbk_p2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_back2;
    private javax.swing.JLabel lbl_blastgif;
    private javax.swing.JLabel lbl_blastgifp2;
    private javax.swing.JLabel lbl_charigif;
    private javax.swing.JLabel lbl_charigifp2;
    private javax.swing.JLabel lbl_gengif;
    private javax.swing.JLabel lbl_gengifp2;
    private javax.swing.JLabel lbl_mkc;
    private javax.swing.JLabel lbl_mkcp2;
    private javax.swing.JLabel lbl_next;
    private javax.swing.JLabel lbl_p1pokename;
    private javax.swing.JLabel lbl_p2pokename1;
    private javax.swing.JLabel lbl_select;
    private javax.swing.JLabel lbl_typhgifp1;
    private javax.swing.JLabel lbl_typhgifp2;
    private javax.swing.JLabel lbl_vengifP1;
    private javax.swing.JLabel lbl_vengifP2;
    // End of variables declaration//GEN-END:variables
}
