/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test1;

import java.awt.Toolkit;

/**
 *
 * @author $$Goutham...!!$$
 */
public class Frame4 extends javax.swing.JFrame {

    /**
     * Creates new form Frame4
     */
    public Frame4() {
      this.setUndecorated(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_typhp2 = new javax.swing.JLabel();
        lbl_typhp1 = new javax.swing.JLabel();
        lbl_charip2 = new javax.swing.JLabel();
        lbl_charip1 = new javax.swing.JLabel();
        lbl_gengarp2 = new javax.swing.JLabel();
        lbl_gengarp1 = new javax.swing.JLabel();
        lbl_blastp2 = new javax.swing.JLabel();
        lbl_blastp1 = new javax.swing.JLabel();
        lbl_venep1 = new javax.swing.JLabel();
        lbl_venep2 = new javax.swing.JLabel();
        lbl_back = new javax.swing.JLabel();
        btn_battle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl_typhp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go4typh.jpg"))); // NOI18N
        getContentPane().add(lbl_typhp2);
        lbl_typhp2.setBounds(1160, 170, 750, 580);

        lbl_typhp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go4typh.jpg"))); // NOI18N
        getContentPane().add(lbl_typhp1);
        lbl_typhp1.setBounds(20, 170, 750, 580);

        lbl_charip2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go4 char.png"))); // NOI18N
        getContentPane().add(lbl_charip2);
        lbl_charip2.setBounds(1140, 110, 760, 720);

        lbl_charip1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go4 char.png"))); // NOI18N
        getContentPane().add(lbl_charip1);
        lbl_charip1.setBounds(50, 50, 720, 720);

        lbl_gengarp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go5.jpg"))); // NOI18N
        getContentPane().add(lbl_gengarp2);
        lbl_gengarp2.setBounds(1300, 110, 550, 670);

        lbl_gengarp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go5.jpg"))); // NOI18N
        getContentPane().add(lbl_gengarp1);
        lbl_gengarp1.setBounds(150, 110, 550, 670);

        lbl_blastp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go2.jpg"))); // NOI18N
        getContentPane().add(lbl_blastp2);
        lbl_blastp2.setBounds(1250, 120, 620, 610);

        lbl_blastp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go2.jpg"))); // NOI18N
        getContentPane().add(lbl_blastp1);
        lbl_blastp1.setBounds(120, 140, 620, 580);

        lbl_venep1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go1.jpg"))); // NOI18N
        getContentPane().add(lbl_venep1);
        lbl_venep1.setBounds(90, 150, 640, 560);

        lbl_venep2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/go1.jpg"))); // NOI18N
        getContentPane().add(lbl_venep2);
        lbl_venep2.setBounds(1230, 140, 650, 570);

        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/frame4back.jpg"))); // NOI18N
        getContentPane().add(lbl_back);
        lbl_back.setBounds(0, 0, 1920, 1080);

        btn_battle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_battleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_battle);
        btn_battle.setBounds(800, 350, 330, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_battleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_battleActionPerformed
        // TODO add your handling code here:
        new Frame3().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_battleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_battle;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_blastp1;
    private javax.swing.JLabel lbl_blastp2;
    private javax.swing.JLabel lbl_charip1;
    private javax.swing.JLabel lbl_charip2;
    private javax.swing.JLabel lbl_gengarp1;
    private javax.swing.JLabel lbl_gengarp2;
    private javax.swing.JLabel lbl_typhp1;
    private javax.swing.JLabel lbl_typhp2;
    private javax.swing.JLabel lbl_venep1;
    private javax.swing.JLabel lbl_venep2;
    // End of variables declaration//GEN-END:variables
}
