/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test1;

import java.awt.Toolkit;

/**
 *
 * @author $$Goutham...!!$$
 */
public class Frame3 extends javax.swing.JFrame {

    /**
     * Creates new form Frame3
     */
    public Frame3() {
  this.setUndecorated(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize); 
        lbl_p1.setText(Login.p1name);
        lbl_p2.setText(Login.p2name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lbl_p2 = new javax.swing.JLabel();
        lbl_p1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_p3 = new javax.swing.JLabel();
        lbl_p4 = new javax.swing.JLabel();
        lbl_p5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Bradley Hand ITC", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("VS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(910, 160, 130, 40);

        lbl_p2.setFont(new java.awt.Font("Bradley Hand ITC", 3, 36)); // NOI18N
        lbl_p2.setText("GOUTHAM");
        getContentPane().add(lbl_p2);
        lbl_p2.setBounds(840, 210, 290, 70);

        lbl_p1.setFont(new java.awt.Font("Bradley Hand ITC", 3, 36)); // NOI18N
        lbl_p1.setText("GOUTHAM");
        getContentPane().add(lbl_p1);
        lbl_p1.setBounds(840, 100, 280, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lo.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(850, 280, 240, 370);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pokemon-blue_00396779.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        lbl_p3.setFont(new java.awt.Font("Bradley Hand ITC", 3, 36)); // NOI18N
        lbl_p3.setText("GOUTHAM");
        getContentPane().add(lbl_p3);
        lbl_p3.setBounds(840, 210, 290, 70);

        lbl_p4.setFont(new java.awt.Font("Bradley Hand ITC", 3, 36)); // NOI18N
        lbl_p4.setText("GOUTHAM");
        getContentPane().add(lbl_p4);
        lbl_p4.setBounds(840, 210, 290, 70);

        lbl_p5.setFont(new java.awt.Font("Bradley Hand ITC", 3, 36)); // NOI18N
        lbl_p5.setText("GOUTHAM");
        getContentPane().add(lbl_p5);
        lbl_p5.setBounds(840, 210, 290, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_p1;
    private javax.swing.JLabel lbl_p2;
    private javax.swing.JLabel lbl_p3;
    private javax.swing.JLabel lbl_p4;
    private javax.swing.JLabel lbl_p5;
    // End of variables declaration//GEN-END:variables
}
